name: Divisifieur Workflow
on: [push]
jobs:
  build:
    runs-on : ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Wallah ça commence 
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: C'est chiant...
        run: ./gradlew build

      - name : CA MARCHE PAAAAAAASS
        run: java -jar build/libs/*.jar 3 1

      - name: C'est bon tu peux RP
        uses: actions/upload-artifact@v2
        with:
          name: FiveM
          path: build/libs/*.jar